using System;
using System.Collections;
using System.Collections.Generic;

namespace csharp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
            // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

            int testLimit = 4000000;
            int total = 0;

            List<int> sequence = new List<int>();
            sequence.Add(1);
            sequence.Add(2);
            total += 2;

            int newValue = 0;
            for (int i = 0; i < 1000;i++)
            {
                newValue = sequence[i] + sequence[i + 1];

                if (newValue > testLimit)
                {
                    break;
                }

                if(newValue %2 == 0){
                    total += newValue;
                }

                sequence.Add(newValue);
            }

            Console.WriteLine(total);
            //this took 10 minutes to code.
        }
    }
}
